pipeline:
  identifier: Build_hilarywenyi_reactcalculator_1752423559722
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: Test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1752366913327
        repoName: hilarywenyi/reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: 10m
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: 10m
                  type: Run
              - step:
                  identifier: debug_variables
                  name: Debug Variables
                  spec:
                    command: |
                      echo "=== Debug Info ==="
                      echo "Repository should be: hilarywenyi/reactcalculator"
                      echo "Connector should be: dockerhubconnector"
                      echo "Current directory:"
                      ls -la
                      echo "Dockerfile exists?"
                      ls -la Dockerfile
                  timeout: 5m
                  type: Run
              - step:
                  identifier: Build_and_push_to_Docker
                  name: Build and push to Docker
                  spec:
                    connectorRef: dockerhubconnector
                    repo: <+pipeline.variables.DOCKER_REPO>
                    tags:
                      - latest
                      - <+codebase.commitSha>
                    dockerfile: Dockerfile
                    context: .
                  timeout: 15m
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
  variables:
    - name: DOCKER_REPO
      type: String
      description: hilarywenyi/reactcalculator
      value: <+input>.default("hilarywenyi/reactcalculator")
