pipeline:
  identifier: Build_hilarywenyi_reactcalculator_1752423559722
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: Test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1752366913327
        repoName: hilarywenyi/reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          enabled: true
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: 10m
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: 10m
                  type: Run
              - step:
                  identifier: docker_build_push
                  name: Build and Push Docker Image
                  spec:
                    connectorRef: account.harnessImage
                    repo: <+pipeline.variables.DOCKER_REPO>
                    tags:
                      - latest
                      - <+codebase.commitSha>
                    dockerfile: Dockerfile
                    context: .
                  timeout: 15m
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
  variables:
    - name: DOCKER_REPO
      type: String
      description: e.g. hilarywenyi/reactcalculator
      value: <+input>
